# Generated by Django 2.0.2 on 2018-03-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessapikey',
            name='type',
            field=models.TextField(choices=[('limited_access', 'Limited Access'), ('admin', 'Admin'), ('manager', 'Manager')]),
        ),
    ]
